# Generated by Django 4.2.3 on 2023-09-12 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_cart_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_street_address', models.CharField(max_length=100)),
                ('shipping_city', models.CharField(max_length=50)),
                ('shipping_state', models.CharField(max_length=50)),
                ('shipping_postal_code', models.CharField(max_length=10)),
                ('shipping_country', models.CharField(max_length=50)),
                ('billing_street_address', models.CharField(max_length=100)),
                ('billing_city', models.CharField(max_length=50)),
                ('billing_state', models.CharField(max_length=50)),
                ('billing_postal_code', models.CharField(max_length=10)),
                ('billing_country', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
