# Generated by Django 4.2.3 on 2023-09-12 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_checkoutaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckoutAddress',
        ),
    ]
