# Generated by Django 4.2.3 on 2023-09-13 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_bill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
