# Generated by Django 4.2.3 on 2023-09-13 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_order_cart_alter_order_order_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
