# Generated by Django 4.2.3 on 2023-09-14 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
