# Generated by Django 4.2.3 on 2023-09-14 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_coupon'),
    ]

    operations = [
    ]
