# Generated by Django 5.0.2 on 2024-02-20 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_purchase_id_purchase_created_at_purchase_uid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_desription',
            new_name='product_description',
        ),
    ]
